// <auto-generated />
namespace TiendaOnline.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class RelacionTienda_Calendario : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(RelacionTienda_Calendario));
        
        string IMigrationMetadata.Id
        {
            get { return "202009212309169_Relacion Tienda_Calendario"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
