// <auto-generated />
namespace TiendaOnline.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class ImageHeaderandImageProfile : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ImageHeaderandImageProfile));
        
        string IMigrationMetadata.Id
        {
            get { return "202008131813110_ImageHeader and ImageProfile"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
